In [10]:
import numpy as np

a = np.random.randn(5,1)

In [11]:
print(a)

[[-1.21870987]
 [-0.56691478]
 [-0.78536972]
 [-0.03491374]
 [ 3.35291403]]


In [12]:
print(a.shape)

(5, 1)


In [13]:
print(a.T)

[[-1.21870987 -0.56691478 -0.78536972 -0.03491374  3.35291403]]


In [15]:
x = np.dot(a, a.T)
print(x)

[[  1.48525376e+00   6.90904642e-01   9.57137829e-01   4.25497234e-02
   -4.08622943e+00]
 [  6.90904642e-01   3.21392370e-01   4.45237702e-01   1.97931170e-02
   -1.90081652e+00]
 [  9.57137829e-01   4.45237702e-01   6.16805593e-01   2.74201965e-02
   -2.63327714e+00]
 [  4.25497234e-02   1.97931170e-02   2.74201965e-02   1.21896945e-03
   -1.17062779e-01]
 [ -4.08622943e+00  -1.90081652e+00  -2.63327714e+00  -1.17062779e-01
    1.12420325e+01]]


[[ 1.58782137]
 [ 0.65282942]
 [ 0.62575322]
 [ 0.06352882]
 [-1.03967121]]
